spring:
  application:
    name: economiks
  profiles:
    active: dev
  jpa:
    open-in-view: true
  flyway:
    enabled: true
    baseline-on-migrate: true
jwt:
  secret: ${JWT_SECRET:segredo-padrao-dev-fraco}
  expiration:
    ms: 86400000